### ISSUE TITLE
need to add bug fixes from noresm2.1 into noresm_develop

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/OSLO_AERO#10]
Add the noresm2.1 bug fix for dry-deposition velocity of aerosol, NorESMhub/CAM#111 .

**Comment by gold2718** [comment]
@mvertens, can you list the bugs fixed in the issue description?

**Comment by oyvindseland** [comment]
Is this not already done, at least with respect to dry deposition?

**Comment by mvertens** [comment]
This is done by  https://github.com/NorESMhub/OSLO_AERO/pull/11.
