### ISSUE TITLE
PEM_Ln9_P512.ne30pg3_ne30pg3_mtn14.NFLTHISToslo_v0d.betzy_intel.cam-outfrq9s fails for noresm_develop

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/OSLO_AERO#12]
In noresm_develop - the following PEM test **fails** `PEM_Ln9_P512.ne30pg3_ne30pg3_mtn14.NFLTHISToslo_v0d.betzy_intel.cam-outfrq9s.`

In noresm2_3_develop - the following test **does not fail**:
`PEM_Ln9.f09_f09_mtn14.NF1850norbc.betzy_intel.cam-outfrq9s.cam23`

A solution is to bring the `noresm_develop` branch for the `oslo_aero/src `directory up to date and as close as possible to the `noresm2_3_develop` code.

**Comment by gold2718** [comment]
Fixed by #13
