### ISSUE TITLE
Reorganize source tree

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/OSLO_AERO#5]
In order to facilitate development of Oslo Aero, we should reorganize the current file structure (all files lumped into top-level directory).
One idea is to put all current Fortran code into a source (or src) directory. This would leave room for other directories such as a testing directory (for standalone unit tests).
Another would be to separate the object source files from other source.
Thoughts? @mvertens @ingvisau

**Comment by mvertens** [comment]
@gold2718 - I think this is a great idea.

**Comment by ingvisau** [comment]
@gold2718  - Agree, I think a src, a testing and a object directory sounds good!
